version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  ml-client:
    build: 
      context: ./machine-learning-client
      dockerfile: Dockerfile
    container_name: ml-client
    depends_on:
      - mongodb
    command: ["python", "-u", "ml_client/main.py"]
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./machine-learning-client:/app

  web-app:
    build: 
      context: ./web-app
      dockerfile: Dockerfile
    container_name: web-app
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./web-app:/app

volumes:
  mongo_data:
